version: '3.8'

services:
  vector-health-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TERRA_DEV_ID=${TERRA_DEV_ID}
      - TERRA_API_KEY=${TERRA_API_KEY}
      - TERRA_WEBHOOK_SECRET=${TERRA_WEBHOOK_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL database (if not using external service)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: vector_health
  #     POSTGRES_USER: vector_health_user
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data:

